export enum USER_PROFILE_TYPES {
  GET_USER_PROFILE_QUIZ_DATA_START = "GET_USER_PROFILE_QUIZ_DATA_START",
  GET_USER_PROFILE_QUIZ_DATA_SUCCESS = "GET_USER_PROFILE_QUIZ_DATA_SUCCESS",
  GET_USER_PROFILE_QUIZ_DATA_FAILED = "GET_USER_PROFILE_QUIZ_DATA_FAILED",
  SET_MAIN_OBJECT = "SET_MAIN_OBJECT",
}
